=== Bharanigithub/Intern/day15/invoices.dtd
<!ELEMENT invoices (customer,invoice+)>
<!ELEMENT customer (cust_name,bill_date,bill_no)>
<!ELEMENT invoice (item,quantity,price,S_No)>
<!ELEMENT cust_name (#PCDATA)>
<!ELEMENT bill_date (#PCDATA)>
<!ELEMENT bill_no (#PCDATA)>
<!ELEMENT item (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT S_No (#PCDATA)>

=== Bharanigithub/Intern/day15/invoices.xml
<!DOCTYPE invoices SYSTEM "invoices.dtd">
<invoices>
<customer>
	<cust_name>Bharanidharan</cust_name>
	<bill_date>08/03/2021</bill_date>
	<bill_no>15</bill_no>
</customer>
<invoice>
	<item>Rice</item>
	<quantity>2</quantity>
	<price>150</price>
	<S_No>1</S_No>
</invoice>
<invoice>
	<item>Dhaal</item>
	<quantity>2</quantity>
	<price>100</price>
	<S_No>2</S_No>
</invoice>
</invoices>
